baseURL = 'https://github.com/KrishnaPayyavula/'
languageCode = 'en-us'
title = 'Krishna Payyavula'
theme = 'ananke'


[params]
  description = "Portfolio and technical blog by Krishna Payyavula - Data Engineering Innovator: Enhancing Customer Service at Postnord | MultiCloud | Conversational AI | Node.JS"
  githubURL = "https://github.com/KrishnaPayyavula"
  linkedinURL = "https://www.linkedin.com/in/krishnapayyavula/"